name: CI Always Fail

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Force a failure
        run: |
          echo "This job is supposed to fail!"
          exit 1   # <-- always fails
