name: CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running simple test..."
          # Simulate a failure sometimes
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "Simulated failure"
            exit 1
          fi
          echo "All tests passed"
