name: CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running simple test..."
          # Simulate a failure 50% of the time
          RANDOM_FAIL=$((RANDOM % 2))
          if [ $RANDOM_FAIL -eq 0 ]; then
            echo "Simulated failure"
            exit 1   # <-- This makes the job fail
          fi
          echo "All tests passed"
